chore(commitizen): rename variables and commands for consistency and clarity in Taskfile.yml to improve maintainability and readability

diff --git a/.config/commitizen/Taskfile.yml b/.config/commitizen/Taskfile.yml
--- a/.config/commitizen/Taskfile.yml
+++ b/.config/commitizen/Taskfile.yml
@@ -2,23 +2,24 @@
 version: "3"
 
 vars:
-  TASK_CZ_VIRTUALENV: '{{.OVERRIDE_TASK_CZ_VIRTUALENV | default "./venv/commitizen"}}'
-  TASK_CZ_COMMAND: '{{.OVERRIDE_TASK_CZ_COMMAND | default "./venv/commitizen/bin/cz"}}'
-  TASK_CZ_CONFIG_FULL_PATH: '{{.OVERRIDE_TASK_CZ_CONFIG_FULL_PATH | default ".config/commitizen/cz.yaml"}}'
-  TASK_CZ_CLI_OPTS: '{{.OVERRIDE_TASK_CZ_CLI_OPTS | default ""}}'
-  TASK_CZ_CLI_CHECK_OPTS: '{{.OVERRIDE_TASK_CZ_CLI_CHECK_OPTS | default "--rev-range origin/main..HEAD"}}'
-  TASK_CZ_PYTHON_VERSION_FILE: '{{.OVERRIDE_TASK_CZ_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
-  TASK_CZ_REQUIREMENTS_FILE: '{{.OVERRIDE_TASK_CZ_REQUIREMENTS_FILE | default ".config/commitizen/requirements.txt"}}'
-  TASK_CZ_BUMP_DRY_RUN: '{{.OVERRIDE_TASK_CZ_BUMP_DRY_RUN | default "false"}}'
-  TASK_CZ_BUMP_YES: '{{.OVERRIDE_TASK_CZ_BUMP_YES | default "false"}}'
-  TASK_CZ_BUMP_CHECK_CONSISTENCY: '{{.OVERRIDE_TASK_CZ_BUMP_CHECK_CONSISTENCY | default "true"}}'
-  TASK_CZ_BUMP_NO_RAISE: '{{.OVERRIDE_TASK_CZ_BUMP_NO_RAISE | default "21"}}'
-  TASK_CZ_BUMP_CHANGELOG: '{{.OVERRIDE_TASK_CZ_BUMP_CHANGELOG | default "false"}}'
-  TASK_CZ_BUMP_PRERELEASE: '{{.OVERRIDE_TASK_CZ_BUMP_PRERELEASE | default ""}}'
-  TASK_CZ_BUMP_DEV_RELEASE: '{{.OVERRIDE_TASK_CZ_BUMP_DEV_RELEASE | default ""}}'
-  TASK_CZ_DEFAULT_BRANCH: '{{.OVERRIDE_TASK_CZ_DEFAULT_BRANCH | default "main"}}'
-  TASK_CZ_RELEASE_BRANCH_PATTERN: '{{.OVERRIDE_TASK_CZ_RELEASE_BRANCH_PATTERN | default "^release/"}}'
-  TASK_CZ_GIT_CURRENT_BRANCH:
+  TASK_COMMITIZEN_ENABLED: '{{.OVERRIDE_TASK_COMMITIZEN_ENABLED | default "true"}}'
+  TASK_COMMITIZEN_VIRTUALENV: '{{.OVERRIDE_TASK_COMMITIZEN_VIRTUALENV | default "./venv/commitizen"}}'
+  TASK_COMMITIZEN_COMMAND: '{{.OVERRIDE_TASK_COMMITIZEN_COMMAND | default "./venv/commitizen/bin/cz"}}'
+  TASK_COMMITIZEN_CONFIG_FULL_PATH: '{{.OVERRIDE_TASK_COMMITIZEN_CONFIG_FULL_PATH | default ".config/commitizen/cz.yaml"}}'
+  TASK_COMMITIZEN_CLI_OPTS: '{{.OVERRIDE_TASK_COMMITIZEN_CLI_OPTS | default ""}}'
+  TASK_COMMITIZEN_CLI_CHECK_OPTS: '{{.OVERRIDE_TASK_COMMITIZEN_CLI_CHECK_OPTS | default "--rev-range origin/main..HEAD"}}'
+  TASK_COMMITIZEN_PYTHON_VERSION_FILE: '{{.OVERRIDE_TASK_COMMITIZEN_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
+  TASK_COMMITIZEN_REQUIREMENTS_FILE: '{{.OVERRIDE_TASK_COMMITIZEN_REQUIREMENTS_FILE | default ".config/commitizen/requirements.txt"}}'
+  TASK_COMMITIZEN_BUMP_DRY_RUN: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_DRY_RUN | default "false"}}'
+  TASK_COMMITIZEN_BUMP_YES: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_YES | default "false"}}'
+  TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY | default "true"}}'
+  TASK_COMMITIZEN_BUMP_NO_RAISE: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_NO_RAISE | default "21"}}'
+  TASK_COMMITIZEN_BUMP_CHANGELOG: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_CHANGELOG | default "false"}}'
+  TASK_COMMITIZEN_BUMP_PRERELEASE: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_PRERELEASE | default ""}}'
+  TASK_COMMITIZEN_BUMP_DEV_RELEASE: '{{.OVERRIDE_TASK_COMMITIZEN_BUMP_DEV_RELEASE | default ""}}'
+  TASK_COMMITIZEN_DEFAULT_BRANCH: '{{.OVERRIDE_TASK_COMMITIZEN_DEFAULT_BRANCH | default "main"}}'
+  TASK_COMMITIZEN_RELEASE_BRANCH_PATTERN: '{{.OVERRIDE_TASK_COMMITIZEN_RELEASE_BRANCH_PATTERN | default "^release/"}}'
+  TASK_COMMITIZEN_GIT_CURRENT_BRANCH:
     sh: |
       if [ -n "$CI_COMMIT_REF_NAME" ]; then
         echo "$CI_COMMIT_REF_NAME"
@@ -40,10 +41,10 @@ tasks:
         Executes commitizen to guide the user through creating a standardized commit message.
 
       🔧 Variables:
-        - TASK_CZ_VIRTUALENV: Path to the virtual environment. Default: "./venv/commitizen"
-        - TASK_CZ_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
-        - TASK_CZ_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
-        - TASK_CZ_CLI_OPTS: Command line options for commitizen. Default: ""
+        - TASK_COMMITIZEN_VIRTUALENV: Path to the virtual environment. Default: "./venv/commitizen"
+        - TASK_COMMITIZEN_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
+        - TASK_COMMITIZEN_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
+        - TASK_COMMITIZEN_CLI_OPTS: Command line options for commitizen. Default: ""
 
       🔐 Preconditions:
         - The 'install' task must have been successfully executed.
@@ -55,7 +56,7 @@ tasks:
       📝 Note:
         This task should be executed when creating a new commit.
     cmds:
-      - "{{.TASK_CZ_COMMAND}} --config {{.TASK_CZ_CONFIG_FULL_PATH}} {{.TASK_CZ_CLI_OPTS}} commit {{.CLI_ARGS}}"
+      - "{{.TASK_COMMITIZEN_COMMAND}} --config {{.TASK_COMMITIZEN_CONFIG_FULL_PATH}} {{.TASK_COMMITIZEN_CLI_OPTS}} commit {{.CLI_ARGS}}"
 
   install:
     desc: Set up Commitizen in a virtual environment.
@@ -64,13 +65,13 @@ tasks:
         Configures Commitizen and its dependencies within a controlled virtual environment.
 
       🔧 Variables:
-        - TASK_CZ_PYTHON_VERSION_FILE: Path to the file specifying the Python version.
+        - TASK_COMMITIZEN_PYTHON_VERSION_FILE: Path to the file specifying the Python version.
           Default: ".config/python/.python-version"
           Example content: "3.11"
-        - TASK_CZ_REQUIREMENTS_FILE: Path to the file listing required packages.
+        - TASK_COMMITIZEN_REQUIREMENTS_FILE: Path to the file listing required packages.
           Default: ".config/commitizen/requirements.txt"
           Example content: "commitizen==3.28.0"
-        - TASK_CZ_VIRTUALENV: Location of the virtual environment for Commitizen.
+        - TASK_COMMITIZEN_VIRTUALENV: Location of the virtual environment for Commitizen.
           Default: "./venv/commitizen"
 
       🔐 Preconditions:
@@ -79,8 +80,8 @@ tasks:
         - An active internet connection is required to download Commitizen and its dependencies.
 
       🔄 Execution:
-        1. Creates a new Python virtual environment using the version specified in TASK_CZ_PYTHON_VERSION_FILE.
-        2. Installs Commitizen and its dependencies using the TASK_CZ_REQUIREMENTS_FILE.
+        1. Creates a new Python virtual environment using the version specified in TASK_COMMITIZEN_PYTHON_VERSION_FILE.
+        2. Installs Commitizen and its dependencies using the TASK_COMMITIZEN_REQUIREMENTS_FILE.
         3. Verifies the installation by checking the installed Commitizen version.
 
       📝 Note:
@@ -88,20 +89,20 @@ tasks:
     preconditions:
       - sh: command -v python3 >/dev/null 2>&1
         msg: "❌ Error: Python is not installed. Please install Python before proceeding."
-      - sh: test -f {{.TASK_CZ_PYTHON_VERSION_FILE}}
+      - sh: test -f {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}
         msg: |
-          ❌ Error: missing file {{.TASK_CZ_PYTHON_VERSION_FILE}}.
+          ❌ Error: missing file {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}.
           Please create it as follows:
           ```bash
-          mkdir -p $(dirname "{{.TASK_CZ_PYTHON_VERSION_FILE}}")
-          echo "3.11" > {{.TASK_CZ_PYTHON_VERSION_FILE}}
+          mkdir -p $(dirname "{{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}")
+          echo "3.11" > {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}
           ```
     status:
       - |
-        {{.TASK_CZ_COMMAND}} version | grep -q $(awk -F '==' '{print $2}' {{.TASK_CZ_REQUIREMENTS_FILE}})
+        {{.TASK_COMMITIZEN_COMMAND}} version | grep -q $(awk -F '==' '{print $2}' {{.TASK_COMMITIZEN_REQUIREMENTS_FILE}})
     cmds:
-      - python$(cut -d '=' -f 2 {{.TASK_CZ_PYTHON_VERSION_FILE}}) -m venv {{.TASK_CZ_VIRTUALENV}}
-      - "{{.TASK_CZ_VIRTUALENV}}/bin/pip install -r {{.TASK_CZ_REQUIREMENTS_FILE}}"
+      - python$(cut -d '=' -f 2 {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}) -m venv {{.TASK_COMMITIZEN_VIRTUALENV}}
+      - "{{.TASK_COMMITIZEN_VIRTUALENV}}/bin/pip install -r {{.TASK_COMMITIZEN_REQUIREMENTS_FILE}}"
       - cmd: echo "✅ Commitizen and dependencies are successfully installed in the virtual environment."
         silent: true
 
@@ -113,10 +114,10 @@ tasks:
         Automatically verifies commits using Commitizen rules.
 
       🔧 Variables:
-        - TASK_CZ_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
-        - TASK_CZ_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
-        - TASK_CZ_CLI_OPTS: Additional command line options for commitizen. Default: ""
-        - TASK_CZ_CLI_CHECK_OPTS: Options specific to the check command. Default: "--rev-range origin/main..HEAD"
+        - TASK_COMMITIZEN_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
+        - TASK_COMMITIZEN_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
+        - TASK_COMMITIZEN_CLI_OPTS: Additional command line options for commitizen. Default: ""
+        - TASK_COMMITIZEN_CLI_CHECK_OPTS: Options specific to the check command. Default: "--rev-range origin/main..HEAD"
 
       🔐 Preconditions:
         - The 'install' task must have been successfully executed.
@@ -128,20 +129,30 @@ tasks:
       📝 Note:
         This task verifies that commit messages conform to the Commitizen standards.
         The default behaviour checks commits from main to HEAD, but this can be customised
-        by modifying the TASK_CZ_CLI_CHECK_OPTS variable.
+        by modifying the TASK_COMMITIZEN_CLI_CHECK_OPTS variable.
+    status:
+      - test "{{.TASK_COMMITIZEN_ENABLED}}" = "false"
+    vars:
+      COMMITIZEN_CHECK_COMMAND:
+        sh: echo "{{.TASK_COMMITIZEN_COMMAND}} --config {{.TASK_COMMITIZEN_CONFIG_FULL_PATH}} {{.TASK_COMMITIZEN_CLI_OPTS}} check {{.TASK_COMMITIZEN_CLI_CHECK_OPTS}}"
     cmds:
-      - |
-        if {{.TASK_CZ_COMMAND}} --config {{.TASK_CZ_CONFIG_FULL_PATH}} {{.TASK_CZ_CLI_OPTS}} check {{.TASK_CZ_CLI_CHECK_OPTS}}; then
-          echo "🎉 All commits successfully verified with Commitizen!"
-        else
-          exit_code=$?
-          if [ $exit_code -eq 3 ]; then
-            echo "⚠️  Warning: No commits found in the specified range to verify."
+      - cmd: echo "🔄 Running commitizen check..."
+        silent: true
+      - cmd: echo "{{.COMMITIZEN_CHECK_COMMAND}}"
+        silent: true
+      - cmd: |
+          if {{.COMMITIZEN_CHECK_COMMAND}}; then
+            echo "🎉 All commits successfully verified with Commitizen!"
           else
-            echo "❌ Commitizen check failed with exit code $exit_code"
-            exit $exit_code
+            exit_code=$?
+            if [ $exit_code -eq 3 ]; then
+              echo "⚠️  Warning: No commits found in the specified range to verify."
+            else
+              echo "❌ Commitizen check failed with exit code $exit_code"
+              exit $exit_code
+            fi
           fi
-        fi
+        silent: true
 
   bump:
     deps: [install]
@@ -151,16 +162,16 @@ tasks:
         Increments the version number based on the commit history.
 
       🔧 Variables:
-        - TASK_CZ_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
-        - TASK_CZ_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
-        - TASK_CZ_CLI_OPTS: Additional command line options for commitizen. Default: ""
-        - TASK_CZ_BUMP_DRY_RUN: Whether to perform a dry run. Default: true
-        - TASK_CZ_BUMP_YES: Whether to automatically confirm prompts. Default: false
-        - TASK_CZ_BUMP_CHECK_CONSISTENCY: Whether to check consistency before bumping. Default: true
-        - TASK_CZ_BUMP_NO_RAISE: Comma-separated error codes that won't raise an error. Default: "21"
-        - TASK_CZ_BUMP_CHANGELOG: Whether to update the changelog when bumping. Default: false
-        - TASK_CZ_BUMP_PRERELEASE: Prerelease identifier (e.g., "alpha", "beta"). Default: ""
-        - TASK_CZ_BUMP_DEV_RELEASE: Development release identifier. Default: ""
+        - TASK_COMMITIZEN_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
+        - TASK_COMMITIZEN_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
+        - TASK_COMMITIZEN_CLI_OPTS: Additional command line options for commitizen. Default: ""
+        - TASK_COMMITIZEN_BUMP_DRY_RUN: Whether to perform a dry run. Default: true
+        - TASK_COMMITIZEN_BUMP_YES: Whether to automatically confirm prompts. Default: false
+        - TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY: Whether to check consistency before bumping. Default: true
+        - TASK_COMMITIZEN_BUMP_NO_RAISE: Comma-separated error codes that won't raise an error. Default: "21"
+        - TASK_COMMITIZEN_BUMP_CHANGELOG: Whether to update the changelog when bumping. Default: false
+        - TASK_COMMITIZEN_BUMP_PRERELEASE: Prerelease identifier (e.g., "alpha", "beta"). Default: ""
+        - TASK_COMMITIZEN_BUMP_DEV_RELEASE: Development release identifier. Default: ""
 
       🔐 Preconditions:
         - The 'install' task must have been successfully executed.
@@ -171,52 +182,61 @@ tasks:
 
       📝 Note:
         This task increments the version number based on the commit history.
-        Use TASK_CZ_BUMP_DRY_RUN=false to apply changes, TASK_CZ_BUMP_YES=false to enable confirmations,
-        and TASK_CZ_BUMP_CHECK_CONSISTENCY=false to skip consistency checks if needed.
-        Set TASK_CZ_BUMP_NO_RAISE to a comma-separated list of error codes to ignore specific errors,
-        e.g., TASK_CZ_BUMP_NO_RAISE=21 to ignore the "Nothing to commit" error.
-        Use TASK_CZ_BUMP_PRERELEASE and TASK_CZ_BUMP_DEV_RELEASE for managing pre-releases and development versions.
+        Use TASK_COMMITIZEN_BUMP_DRY_RUN=false to apply changes, TASK_COMMITIZEN_BUMP_YES=false to enable confirmations,
+        and TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY=false to skip consistency checks if needed.
+        Set TASK_COMMITIZEN_BUMP_NO_RAISE to a comma-separated list of error codes to ignore specific errors,
+        e.g., TASK_COMMITIZEN_BUMP_NO_RAISE=21 to ignore the "Nothing to commit" error.
+        Use TASK_COMMITIZEN_BUMP_PRERELEASE and TASK_COMMITIZEN_BUMP_DEV_RELEASE for managing pre-releases and development versions.
     vars:
       BUMP_OPTIONS:
         sh: |
           options=(
-            {{if eq .TASK_CZ_BUMP_YES "true"}}"--yes"{{end}}
-            {{if eq .TASK_CZ_BUMP_DRY_RUN "true"}}"--dry-run"{{end}}
-            {{if eq .TASK_CZ_BUMP_CHECK_CONSISTENCY "true"}}"--check-consistency"{{end}}
-            {{if eq .TASK_CZ_BUMP_CHANGELOG "true"}}"--changelog"{{end}}
+            {{if eq .TASK_COMMITIZEN_BUMP_YES "true"}}"--yes"{{end}}
+            {{if eq .TASK_COMMITIZEN_BUMP_DRY_RUN "true"}}"--dry-run"{{end}}
+            {{if eq .TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY "true"}}"--check-consistency"{{end}}
+            {{if eq .TASK_COMMITIZEN_BUMP_CHANGELOG "true"}}"--changelog"{{end}}
           )
 
-          if [[ "{{.TASK_CZ_GIT_CURRENT_BRANCH}}" =~ {{.TASK_CZ_RELEASE_BRANCH_PATTERN}} ]] || [ -n "{{.TASK_CZ_BUMP_PRERELEASE}}" ]; then
+          if [[ "{{.TASK_COMMITIZEN_GIT_CURRENT_BRANCH}}" =~ {{.TASK_COMMITIZEN_RELEASE_BRANCH_PATTERN}} ]] || [ -n "{{.TASK_COMMITIZEN_BUMP_PRERELEASE}}" ]; then
             options+=("--prerelease")
-          elif [[ "{{.TASK_CZ_GIT_CURRENT_BRANCH}}" != "{{.TASK_CZ_DEFAULT_BRANCH}}" ]] || [ -n "{{.TASK_CZ_BUMP_DEV_RELEASE}}" ]; then
+          elif [[ "{{.TASK_COMMITIZEN_GIT_CURRENT_BRANCH}}" != "{{.TASK_COMMITIZEN_DEFAULT_BRANCH}}" ]] || [ -n "{{.TASK_COMMITIZEN_BUMP_DEV_RELEASE}}" ]; then
             options+=("--devrelease" "$(date +%Y%m%d%H%M%S)")
           fi
 
           echo "${options[@]}"
       CLI_OPTIONS:
         sh: |
-          options=({{.TASK_CZ_CLI_OPTS}})
-          if [ -n "{{.TASK_CZ_BUMP_NO_RAISE}}" ]; then
-            options+=("--no-raise" "{{.TASK_CZ_BUMP_NO_RAISE}}")
+          options=({{.TASK_COMMITIZEN_CLI_OPTS}})
+          if [ -n "{{.TASK_COMMITIZEN_BUMP_NO_RAISE}}" ]; then
+            options+=("--no-raise" "{{.TASK_COMMITIZEN_BUMP_NO_RAISE}}")
           fi
           echo "${options[@]}"
+      COMMITIZEN_BUMP_COMMAND:
+        sh: echo "{{.TASK_COMMITIZEN_COMMAND}} --config {{.TASK_COMMITIZEN_CONFIG_FULL_PATH}} {{.CLI_OPTIONS}} bump {{.BUMP_OPTIONS}}"
+    status:
+      - test "{{.TASK_COMMITIZEN_ENABLED}}" = "false"
     cmds:
-      - |
-        if {{.TASK_CZ_COMMAND}} --config {{.TASK_CZ_CONFIG_FULL_PATH}} {{.CLI_OPTIONS}} bump {{.BUMP_OPTIONS}}; then
-          echo "🎉 All commits successfully verified with Commitizen!"
-        else
-          exit_code=$?
-          if [ $exit_code -eq 3 ]; then
-            echo "⚠️  Warning: No commits found in the specified range to verify."
-          else
-            echo "❌ Commitizen bump failed with exit code $exit_code"
-            exit $exit_code
-          fi
-        fi
+      - cmd: echo "🔄 Running commitizen bump..."
+        silent: true
+      - cmd: echo "{{.COMMITIZEN_BUMP_COMMAND}}"
+        silent: true
       - cmd: |
-          if [ "{{.TASK_CZ_BUMP_DRY_RUN}}" = "true" ]; then
-            echo "🎉 Version bump completed in dry-run mode. No changes were applied."
+          if {{.COMMITIZEN_BUMP_COMMAND}}; then
+            echo "🎉 All commits successfully verified with Commitizen!"
           else
-            echo "✅ Version bump completed successfully!"
+            exit_code=$?
+            if [ $exit_code -eq 3 ]; then
+              echo "⚠️  Warning: No commits found in the specified range to verify."
+            else
+              echo "❌ Commitizen bump failed with exit code $exit_code"
+              exit $exit_code
+            fi
+          fi
+        silent: true
+      - cmd: |
+          if [ "{{.TASK_COMMITIZEN_BUMP_DRY_RUN}}" = "true" ]; then
+            echo "Info : Version bump completed in dry-run mode. No changes were applied."
+          else
+            echo "🎉 Version bump completed successfully!"
           fi
         silent: true
